name: test_ui_1
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^6.2.0
  im_stepper: ^1.0.1+1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
fonts:
  - family: Gothic A1
    fonts:
      - asset: assets/fonts/GothicA1-Regular.ttf
        weight: 400
      - asset: assets/fonts/GothicA1-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/GothicA1-Thin.ttf
        weight: 100
      - asset: assets/fonts/GothicA1-Light.ttf
        weight: 300
      - asset: assets/fonts/GothicA1-Medium.ttf
        weight: 500
      - asset: assets/fonts/GothicA1-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/GothicA1-Bold.ttf
        weight: 700
      - asset: assets/fonts/GothicA1-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/GothicA1-Black.ttf
        weight: 900
